/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class net_aurxenon_JNativeCurses_Input_Input */

#ifndef _Included_net_aurxenon_JNativeCurses_Input_Input
#define _Included_net_aurxenon_JNativeCurses_Input_Input
#include <stddef.h>
#include <jni.h>
#include <curses.h>
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_aurxenon_JNativeCurses_Input_Input
 * Method:    inputInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_aurxenon_JNativeCurses_Input_Input_inputInit
  (JNIEnv *, jobject);

/*
 * Class:     net_aurxenon_JNativeCurses_Input_Input
 * Method:    readInput
 * Signature: ()C
 */
JNIEXPORT jint JNICALL Java_net_aurxenon_JNativeCurses_Input_Input_readInput
  (JNIEnv *, jobject);

/*
 * Class:     net_aurxenon_JNativeCurses_Input_Input
 * Method:    enableKeyDelay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_aurxenon_JNativeCurses_Input_Input_enableKeyDelay
  (JNIEnv *, jobject);

/*
 * Class:     net_aurxenon_JNativeCurses_Input_Input
 * Method:    disableKeyDelay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_aurxenon_JNativeCurses_Input_Input_disableKeyDelay
  (JNIEnv *, jobject);

/*
 * Class:     net_aurxenon_JNativeCurses_Input_Input
 * Method:    enableEcho
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_aurxenon_JNativeCurses_Input_Input_enableEcho
  (JNIEnv *, jobject);

/*
 * Class:     net_aurxenon_JNativeCurses_Input_Input
 * Method:    disableEcho
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_aurxenon_JNativeCurses_Input_Input_disableEcho
  (JNIEnv *, jobject);

/*
 * Class:     net_aurxenon_JNativeCurses_Input_Input
 * Method:    enableLongText
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_aurxenon_JNativeCurses_Input_Input_enableLongText
  (JNIEnv *, jobject);

/*
 * Class:     net_aurxenon_JNativeCurses_Input_Input
 * Method:    disableLongText
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_aurxenon_JNativeCurses_Input_Input_disableLongText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
