/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class net_aurxenon_JNativeCurses_Display_Display */

#ifndef _Included_net_aurxenon_JNativeCurses_Display_Display
#define _Included_net_aurxenon_JNativeCurses_Display_Display
#include <stddef.h>
#include <jni.h>
#include <curses.h>
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_aurxenon_JNativeCurses_Display_Display
 * Method:    displayInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_aurxenon_JNativeCurses_Display_Display_displayInit
  (JNIEnv *, jobject);

/*
 * Class:     net_aurxenon_JNativeCurses_Display_Display
 * Method:    clearScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_aurxenon_JNativeCurses_Display_Display_clearScreen
  (JNIEnv *, jobject);

/*
 * Class:     net_aurxenon_JNativeCurses_Display_Display
 * Method:    nativeDrawCharacter
 * Signature: (CIISSSSSS)V
 */
JNIEXPORT void JNICALL Java_net_aurxenon_JNativeCurses_Display_Display_nativeDrawCharacter
  (JNIEnv *, jobject, jchar, jint, jint, jint, jint);

/*
 * Class:     net_aurxenon_JNativeCurses_Display_Display
 * Method:    nativeDrawText
 * Signature: (Ljava/lang/String;IISSSSSS)V
 */
JNIEXPORT void JNICALL Java_net_aurxenon_JNativeCurses_Display_Display_nativeDrawText
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     net_aurxenon_JNativeCurses_Display_Display
 * Method:    finishRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_aurxenon_JNativeCurses_Display_Display_finishRender
  (JNIEnv *, jobject)

/*
 * Class:     net_aurxenon_JNativeCurses_Display_Display
 * Method:    hideCursor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_aurxenon_JNativeCurses_Display_Display_hideCursor
  (JNIEnv *, jobject);

/*
 * Class:     net_aurxenon_JNativeCurses_Display_Display
 * Method:    showCursor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_aurxenon_JNativeCurses_Display_Display_showCursor
  (JNIEnv *, jobject);

/*
 * Class:     net_aurxenon_JNativeCurses_Display_Display
 * Method:    getMaxTerminalHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_aurxenon_JNativeCurses_Display_Display_getMaxTerminalHeight
  (JNIEnv *, jobject);

/*
 * Class:     net_aurxenon_JNativeCurses_Display_Display
 * Method:    getMaxTerminalWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_aurxenon_JNativeCurses_Display_Display_getMaxTerminalWidth
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
